services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'moviesdh'
      MYSQL_USER: 'Juan'
      MYSQL_PASSWORD: 'camIlo.j3524'
      MYSQL_ROOT_PASSWORD: 'camIlo.j3524'
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3307
    ports:
      - 3307:3306